version: "3.9"

services:
  backend:
    build:
      context: ../
      dockerfile: Dockerfile
    image: vowser/backend:dev
    env_file:
      ../.env
    environment:
      SPRING_PROFILES_ACTIVE: local
    ports:
      - "4001:4001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4001/actuator/health"]
      interval: 30s
      retries: 5