version: "3.9"

services:
  backend:
    build:
      context: ../
      dockerfile: Dockerfile
    image: vowser/backend:dev
    env_file:
      ../.env
    environment:
      SPRING_PROFILES_ACTIVE: local
    ports:
      - "4001:4001"
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4001/actuator/health"]
      interval: 30s
      retries: 5

  mariadb:
    image: mariadb:11
    env_file: ../.env
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "bash -c 'healthcheck.sh --connect'"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  redis:
    image: redis:7
    command: ["redis-server","--appendonly","yes"]
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5

volumes:
  mariadb_data:
  redis_data: