spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  application:
    name: vowser-backend

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5

  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
    redis:
      host: ${SPRING_DATA_REDIS_HOST:redis}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      timeout: 3000

  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

  jackson:
    default-property-inclusion: non_null

management:
  endpoints:
    web:
      exposure:
        include: health,info

playwright:
  ws-endpoint: ${PLAYWRIGHT_WS_ENDPOINT}

#ai:
#  gemini:
#    api-key: ${GEMINI_API_KEY}

logging:
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
