spring:
  devtools:
    restart:
      enabled: true
  cache:
    type: none

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    com.vowser.backend: DEBUG