server:
  forward-headers-strategy: native

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations:
      - classpath:db/migration

logging:
  level:
    ROOT: INFO
    # 특정 패키지에 대한 디버그가 필요할 경우 아래 주석을 해제하여 사용
    # com.vowser.backend: DEBUG
  file:
    name: /var/log/vowser/backend.log