spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate.format_sql: true

  flyway:
    enabled: false

  devtools:
    restart:
      enabled: true

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    com.vowser.backend: DEBUG