server:
  forward-headers-strategy: native

spring:
  datasource:
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

logging:
  level:
    org.springframework.web: WARN
    org.hibernate.SQL: WARN
    com.vowser.backend: INFO
  file:
    name: /var/log/vowser/backend.log
