spring:
  profiles:
    group:
      "local": "local"
      "deploy": "deploy"
    active: ${SPRING_PROFILES_ACTIVE:local}
  application:
    name: vowser-backend

  cloud:
    compatibility-verifier:
      enabled: false


  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

  jackson:
    default-property-inclusion: non_null

management:
  endpoints:
    web:
      exposure:
        include: health,info

gcp:
  project-id: "sixth-radar-463501-n1"
  location: "global"

google:
  cloud:
    credentials:
      json: ${GOOGLE_CREDENTIALS_JSON:}



logging:
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS

speech:
  language-code: ko-KR
  model: long

websocket:
  timeout:
    write: 10
    connect: 30

network:
  google-cloud:
    https-port: 443
  data:
    bytes-per-kb: 1024

mcp:
  search:
    path-limit: 3

content:
  types:
    text: "text"
    image: "image"

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
#  default-produces-media-type: application/json
#  default-consumes-media-type: application/json